name: detect-file-changes
'on':
  workflow_call:
    outputs:
      rust_changed:
        description: True if Rust files changed.
        value: ${{ jobs.changes.outputs.rust_changed }}
      bold_legacy_changed:
        description: True if Bold Legacy or related files changed.
        value: ${{ jobs.changes.outputs.bold_legacy_changed }}
      changelog_added:
        description: New changelog fragments.
        value: ${{ jobs.changes.outputs.changelog_added }}
jobs:
  changes:
    name: Detect file changes
    runs-on: ubuntu-latest
    outputs:
      rust_changed: ${{ steps.changed.outputs.rust_any_changed }}
      bold_legacy_changed: ${{ steps.changed.outputs.bold_legacy_any_changed }}
      changelog_added: ${{ steps.changed.outputs.changelog_added_files }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 10
        persist-credentials: true
    - name: Detect changes
      id: changed
      uses: tj-actions/changed-files@v47
      with:
        files_yaml: "rust:\n  - 'crates/**'\n  - 'contracts/**'\n  - 'Makefile'\n\
          \  - '**.toml'\n  - '**/Cargo.lock'\n  - '.github/workflows/_rust-tests.yml'\n\
          \  - '.github/workflows/_detect-changes.yml'\nbold_legacy:\n  - 'bold/legacy/**'\n\
          \  - '.github/workflows/_bold-legacy.yml'\nchangelog:\n  - 'changelog/**.md'\n"
