name: CI
run-name: CI triggered from @${{ github.actor }} of ${{ github.head_ref }}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref
    }}
  cancel-in-progress: true
'on':
  workflow_dispatch: null
  pull_request: null
jobs:
  changes:
    uses: ./.github/workflows/_detect-changes.yml
    secrets: inherit
  fast:
    uses: ./.github/workflows/_fast.yml
    secrets: inherit
  rust-tests:
    needs: changes
    if: needs.changes.outputs.rust_changed == 'true'
    uses: ./.github/workflows/_rust-tests.yml
    secrets: inherit
  bold-legacy:
    needs: changes
    if: needs.changes.outputs.bold_legacy_changed == 'true'
    uses: ./.github/workflows/_bold-legacy.yml
    secrets: inherit
  go-tests:
    uses: ./.github/workflows/_standard-go-test-suite.yml
    secrets: inherit
  validation-tests:
    uses: ./.github/workflows/_validation-tests.yml
    secrets: inherit
  codecov:
    needs:
    - go-tests
    - rust-tests
    if: always()
    uses: ./.github/workflows/_codecov.yml
    secrets: inherit
    permissions:
      pull-requests: write
    with:
      post_comment: true
      upload_report: false
  changelog:
    needs: changes
    uses: ./.github/workflows/_changelog.yml
    secrets: inherit
    with:
      changelog_fragments: ${{ needs.changes.outputs.changelog_added }}
  can_proceed:
    name: can_proceed
    runs-on: ubuntu-latest
    needs:
    - fast
    - changelog
    steps:
    - name: OK
      run: exit 0
  can_see_status:
    runs-on: ubuntu-latest
    steps:
    - run: true
