name: Check Design Approved
'on':
  merge_group: null
  pull_request_target:
    branches:
    - master
    - main
    types:
    - synchronize
    - opened
    - reopened
    - labeled
    - unlabeled
permissions:
  statuses: write
jobs:
  check-design-approved:
    name: Check if Design Approved
    runs-on: ubuntu-latest
    steps:
    - name: Check if design approved and update status
      run: "set -euo pipefail\nrepo_url=\"${{ github.api_url }}/repos/$GITHUB_REPOSITORY\"\
        \ncommit_sha=\"${{ github.event.pull_request.head.sha || github.sha }}\"\n\
        status_state=\"success\"  # default to success\n\nif [[ \"$GITHUB_EVENT_NAME\"\
        \ == \"pull_request\" || \"$GITHUB_EVENT_NAME\" == \"pull_request_target\"\
        \ ]]; then\n  design_approved='${{ contains(github.event.pull_request.labels.*.name,\
        \ 'design-approved') }}'\n  after_next_version='${{ contains(github.event.pull_request.labels.*.name,\
        \ 'after-next-version') }}'\n  status_state=\"pending\"\n  if [[ \"$design_approved\"\
        \ == \"true\" && \"$after_next_version\" != \"true\" ]]; then\n    status_state=\"\
        success\"\n  fi\nfi\n\ncurl -sSL --fail-with-body \\\n  -X POST \\\n  -H \"\
        Accept: application/vnd.github+json\" \\\n  -H \"Authorization: Bearer ${{\
        \ secrets.GITHUB_TOKEN }}\" \\\n  -H \"X-GitHub-Api-Version: 2022-11-28\"\
        \ \\\n  \"${repo_url}/statuses/$commit_sha\" \\\n  -d '{\"context\":\"Design\
        \ Approved Check\",\"state\":\"'\"$status_state\"'\"}'\n"
