name: Merge CI
run-name: Merge CI triggered from @${{ github.actor }} of ${{ github.head_ref }}
'on':
  merge_group: null
jobs:
  changes:
    uses: ./.github/workflows/_detect-changes.yml
    secrets: inherit
  fast:
    uses: ./.github/workflows/_fast.yml
    secrets: inherit
  rust-tests:
    needs: changes
    if: needs.changes.outputs.rust_changed == 'true'
    uses: ./.github/workflows/_rust-tests.yml
    secrets: inherit
  bold-legacy:
    needs: changes
    if: needs.changes.outputs.bold_legacy_changed == 'true'
    uses: ./.github/workflows/_bold-legacy.yml
    secrets: inherit
  go-tests:
    uses: ./.github/workflows/_standard-go-test-suite.yml
    secrets: inherit
  codecov:
    needs:
    - go-tests
    - rust-tests
    if: always()
    uses: ./.github/workflows/_codecov.yml
    secrets: inherit
    permissions:
      pull-requests: write
    with:
      post_comment: false
      upload_report: true
  can_proceed:
    runs-on: ubuntu-latest
    needs:
    - fast
    - rust-tests
    - bold-legacy
    - go-tests
    if: always()
    steps:
    - name: Aggregate results
      run: "fast_result=\"${{ needs.fast.result }}\"\ngo_tests_result=\"${{ needs['go-tests'].result\
        \ }}\"\nrust_tests_result=\"${{ needs['rust-tests'].result }}\"\nbold_legacy_result=\"\
        ${{ needs['bold-legacy'].result }}\"\nok=1\nif [ \"$fast_result\" != \"success\"\
        \ ]; then\n  ok=0\n  echo \"Fast job failed or was skipped\"\nfi\nif [ \"\
        $go_tests_result\" != \"success\" ]; then\n  ok=0\n  echo \"Go tests job failed\
        \ or was skipped\"\nfi\nif [ \"$rust_tests_result\" != \"success\" ] && [\
        \ \"$rust_tests_result\" != \"skipped\" ]; then\n  ok=0\n  echo \"Rust job\
        \ failed\"\nfi\nif [ \"$bold_legacy_result\" != \"success\" ] && [ \"$bold_legacy_result\"\
        \ != \"skipped\" ]; then\n  ok=0\n  echo \"Bold Legacy job failed\"\nfi\n\
        if [ $ok -eq 1 ]; then\n  echo \"All required jobs passed or were skipped\"\
        \n  exit 0\nelse\n  echo \"One or more required jobs failed\"\n  exit 1\n\
        fi\n"
  can_see_status:
    runs-on: ubuntu-latest
    steps:
    - run: true
